const WA="916200171750",money=n=>"₹"+Math.round(n).toLocaleString("en-IN");
const data={cakes:[
["chocolate","Chocolate Cake","चॉकलेट केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}],
["vanilla","Vanilla Cake","वेनिला केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}],
["pineapple","Pineapple Cake","पाइनएप्पल केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}],
["butterscotch","Butterscotch Cake","बटरस्कॉच केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}],
["white-forest","White Forest Cake","व्हाइट फॉरेस्ट केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}],
["strawberry","Strawberry Cake","स्ट्रॉबेरी केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}],
["blueberry","Blueberry Cake","ब्लूबेरी केक",{"0.5":150,1:250,2:500,3:750,5:1250,7:1750}]],
pastries:[["pastry","Pastry","सभी प्रकार की पेस्ट्री",20]],cupcakes:[["cupcake","Cup Cake","सभी प्रकार के कप केक",15]],items:[["balloon","Birthday Balloon","बर्थडे बैलून",[50,100]],["cap","Birthday Cap","बर्थडे कैप",[10,100]],["candle","Cake Candle","केक कैंडल",[10,100]],["banner","Cake Decoration Banner","केक डेकोरेशन बैनर",[50,300]],["fog","Fog / Spray","फॉग / स्प्रे",[50,150]]]};
let cart=[];
function render(cat="cakes"){document.querySelectorAll(".cat").forEach(x=>x.classList.toggle("active",x.dataset.cat==cat));document.getElementById("product-list").innerHTML=data[cat].map((p,i)=>{let price=Array.isArray(p[3])?`${money(p[3][0])} – ${money(p[3][1])}`:typeof p[3]=="object"?"":money(p[3]);return `<article class="product"><div class="product-top">${cat=="cakes"?"🎂":cat=="pastries"?"🍰":cat=="cupcakes"?"🧁":"🎈"}</div><div class="product-body"><h3>${p[1]}</h3><p>${p[2]}</p>${cat=="cakes"?`<select id="s-${p[0]}"><option value=".5">½ Pound — ₹150</option><option value="1">1 Pound — ₹250</option><option value="2">2 Pound — ₹500</option><option value="3">3 Pound — ₹750</option><option value="5">5 Pound — ₹1,250</option><option value="7">7 Pound — ₹1,750</option></select>`:`<b>${price}</b>`}${Array.isArray(p[3])?`<small><br>type/design के अनुसार final price confirm होगा।</small>`:""}<button class="btn" style="width:100%;margin-top:12px" onclick="add('${cat}',${i})">Add to Order</button></div></article>`}).join("")}
function add(cat,i){let p=data[cat][i],size="",price=typeof p[3]=="object"&&!Array.isArray(p[3])?p[3][document.getElementById("s-"+p[0]).value]:Array.isArray(p[3])?p[3][0]:p[3];if(cat=="cakes")size=document.getElementById("s-"+p[0]).value;let key=p[0]+size,e=cart.find(x=>x.key==key);if(e)e.q++;else cart.push({key,name:p[1],size,price,q:1,range:Array.isArray(p[3])});draw();document.getElementById("order").scrollIntoView({behavior:"smooth"})}
function delivery(){return document.getElementById("mode").value=="delivery"?Number(document.getElementById("dist").value||0)*20:0}
function draw(){let c=document.getElementById("cart");c.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><b>${x.name}</b><small>${x.size?x.size+" Pound • ":""}${money(x.price)} × ${x.q}${x.range?" • starting price":""}</small></div><div class="qty"><button onclick="qty(${i},-1)">−</button> ${x.q} <button onclick="qty(${i},1)">+</button></div></div>`).join(""):"<p>अभी कोई item नहीं चुना गया है।</p>";let it=cart.reduce((s,x)=>s+x.price*x.q,0),d=delivery();document.getElementById("itemsTotal").textContent=money(it);document.getElementById("deliveryTotal").textContent=money(d);document.getElementById("grandTotal").textContent=money(it+d)}
function qty(i,d){cart[i].q+=d;if(cart[i].q<1)cart.splice(i,1);draw()}
document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>render(b.dataset.cat));
document.getElementById("mode").onchange=()=>{let d=document.getElementById("mode").value=="delivery";document.getElementById("distBox").classList.toggle("hide",!d);document.getElementById("addrBox").classList.toggle("hide",!d);document.getElementById("dist").required=d;document.getElementById("addr").required=d;draw()};document.getElementById("dist").oninput=draw;
document.getElementById("form").onsubmit=e=>{e.preventDefault();if(!cart.length)return alert("कृपया पहले कोई product चुनें।");let name=document.getElementById("name").value.trim(),phone=document.getElementById("phone").value.trim(),mode=document.getElementById("mode").value,dist=Number(document.getElementById("dist").value||0),addr=document.getElementById("addr").value.trim(),msg=document.getElementById("message").value.trim(),pay=document.getElementById("payment").value,it=cart.reduce((s,x)=>s+x.price*x.q,0),del=delivery(),total=it+del;let lines=["🍰 *PREM CAKE HOUSE ORDER*","",`👤 नाम: ${name}`,`📞 फोन: ${phone}`,"","*🧾 ORDER DETAILS*"];cart.forEach(x=>lines.push(`${x.name}${x.size?" — "+x.size+" Pound":""} × ${x.q} — ${money(x.price*x.q)}${x.range?" (starting price)":""}`));lines.push("",`🛍️ सामान की कीमत: ${money(it)}`);if(mode=="delivery")lines.push(`🛵 Delivery: ${dist} km × ₹20 = ${money(del)}`,`📍 पता: ${addr}`);else lines.push("🏪 Shop Pickup: FREE");lines.push(`💰 *कुल कीमत: ${money(total)}*`,`💳 Payment: ${pay}`);if(msg)lines.push("",`🎂 Cake Message: ${msg}`);lines.push("","🎉 *आपका ऑर्डर सफलतापूर्वक बुक हो गया है!*","🙏 धन्यवाद! Prem Cake House में आपका स्वागत है ❤️","", "कृपया details check करके WhatsApp पर Send करें।");let url="https://wa.me/"+WA+"?text="+encodeURIComponent(lines.join("\n"));let r=document.getElementById("result");r.classList.remove("hide");r.innerHTML=`<h3>Order Message Ready! 🎉</h3><p>पूरा order WhatsApp के लिए तैयार है।</p><a class="btn wa" target="_blank" href="${url}">📱 Open WhatsApp & Send</a><p><small>नोट: Balloon, Cap, Candle, Banner और Fog/Spray की final price bakery confirm करेगा।</small></p>`;window.open(url,"_blank")};
render();draw();